### ISSUE TITLE
BUGS 2.1 Chat box changes size when a long message is deleted

### ISSUE THREAD

**Issue by fran-netizen** [Error-404-Project-W25/Error-404-SOEN341_Project_W25#71]
- Modify chat box to maintain current size when message is deleted

**Comment by TheLonelyOtaku315** [comment]
## **Possible Solution**
To maintain the chat box size, update the chatLog.css ```.chat-box``` width to:
```css
.chat-box {
    width: calc(100% - 35rem); /* Maintain consistent width */
}
```
### **Breakdown of 35rem Calculation:**
- **Sidebar 1:** 5rem
- **Sidebar 2:** 15rem
- **Team List:** 15rem
- **Total Used Space:** 35rem

This ensures the chat box always takes up the remaining space, preventing unwanted resizing.
